# Generated by Django 3.1.13 on 2021-09-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0077_auto_20210819_1119"),
    ]

    operations = [
        migrations.AddField(
            model_name="editor",
            name="ignore_wp_bundle_eligible",
            field=models.BooleanField(
                default=False, help_text="Ignore all criteria for bundle access?"
            ),
        ),
    ]
